//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace TestGap.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        public Paciente()
        {
            
        }

        [Required]
        [Display(Name = "Id Paciente")]
        public int Id_Paciente { get; set; }

        [Required]
        [Display(Name = "Nombre")]
        public string Nombre { get; set; }

        [Required]
        [Display(Name = "Identificacion")]
        public string Identificacion { get; set; }

        [Required]
        [Display(Name = "Edad")]
        [DataType(DataType.Duration)]
        public short Edad { get; set; }

        [Required]
        [Display(Name = "Correo")]
        [DataType(DataType.EmailAddress)]
        public string Correo { get; set; }

        [Required]
        [Display(Name = "Telefono")]
        [DataType(DataType.PhoneNumber)]
        public string Telefono { get; set; }

        [Required]
        [Display(Name = "Fecha Ultima Visita")]
        [DataType(DataType.DateTime)]
        public Nullable<System.DateTime> Fecha_Ultima_Visita { get; set; }

        [Required]
        [Display(Name = "Fecha Proxima Visita")]
        [DataType(DataType.DateTime)]
        public Nullable<System.DateTime> Fecha_Proxima_Visita { get; set; }
    
        public virtual List<Tratamiento> Tratamientos { get; set; }
    }
}
