//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace TestGap.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tratamiento
    {
        [Required]
        [Display(Name = "Id Tratamiento")]
        public int Id_Tratamiento { get; set; }

        [Required]
        [Display(Name = "Id Paciente")]
        public int Id_Paciente { get; set; }

        [Required]
        [Display(Name = "Fecha Inicio")]
        [DataType(DataType.DateTime)]
        public System.DateTime Fecha_Inicio { get; set; }

        [Required]
        [Display(Name = "Fecha Fin")]
        [DataType(DataType.DateTime)]
        public System.DateTime Fecha_Fin { get; set; }

        [Required]
        [Display(Name = "Costo")]
        [DataType(DataType.Duration)]
        public int Costo { get; set; }

        [Required]
        [Display(Name = "Detalle")]
        public string Detalle { get; set; }
    
        public virtual Paciente Paciente { get; set; }
    }
}
